# Generated by Django 5.2.7 on 2025-11-23 11:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20, unique=True)),
                ('floor', models.CharField(choices=[('B1', 'Basement 1'), ('G', 'Ground Floor'), ('1', 'First Floor'), ('2', 'Second Floor'), ('3', 'Third Floor')], default='G', max_length=3)),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('slot_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('valet', 'Valet'), ('covered', 'Covered')], default='standard', max_length=20)),
                ('slot_size', models.CharField(choices=[('compact', 'Compact'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('base_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('premium_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_ev_charging', models.BooleanField(default=False)),
                ('is_handicap_accessible', models.BooleanField(default=False)),
                ('is_covered', models.BooleanField(default=False)),
                ('has_security_camera', models.BooleanField(default=False)),
                ('distance_from_elevator', models.IntegerField(default=50)),
                ('distance_from_exit', models.IntegerField(default=100)),
                ('location_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parking Slot',
                'verbose_name_plural': 'Parking Slots',
                'db_table': 'api_parkingslot',
                'ordering': ['floor', 'zone', 'slot_number'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=20)),
                ('booked_at', models.DateTimeField()),
                ('released_at', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to=settings.AUTH_USER_MODEL)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='api.parkingslot')),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'db_table': 'api_bookinghistory',
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('start_time', models.DateTimeField()),
                ('expected_end_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('compact', 'Compact Car'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle')], default='sedan', max_length=20)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('premium_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('special_requirements', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.parkingslot')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'api_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('digital_wallet', 'Digital Wallet')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'api_payment',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
